In [42]:
import json
import csv
import pandas as pd
import numpy as np

In [43]:
# Loading small Cisco logs
sourceFile = open("tests.json", 'r')
json_file= json.load(sourceFile)

In [44]:
# Loading large Cisco logs
sourceFile_2 = open("dump.json", 'r')
json_file_2= json.load(sourceFile_2)

### Creating functions to calculate execution time for each test case

In [45]:
def splittint_time(time_data):
    
    time_data = time_data.split('T')
    date = time_data[0]
    time_data = time_data[1].split('+')
    h, m, s = time_data[0].split(':')
    return date, h, m, s
 
    
    
def time_in_sec(start_time, finish_time):
    sd, sh, sm, ss = splittint_time(start_time)
    fd, fh, fm, fs = splittint_time(finish_time)    
    
    if int(sh) > int(fh):
        finished_in_sec = ((int(fh)+24) * 3600 + int(fm) * 60 + int(fs))
        started_in_sec = (int(sh) * 3600 + int(sm) * 60 + int(ss))
        exec_time = finished_in_sec - started_in_sec
    else:
        finished_in_sec = (int(fh) * 3600 + int(fm) * 60 + int(fs))
        started_in_sec = (int(sh) * 3600 + int(sm) * 60 + int(ss))
        exec_time = finished_in_sec - started_in_sec
        
    return exec_time, (sh), sd

### Function to extract all the features for each test case

In [46]:
def extract_information(result_list):
    exec_time = 0
    st_hour = 0
    starting_date = 0

    length_list.append(len(results))
    failure_list = []
    for each_results in range(len(result_list)):  
        failure_list.append(results[each_results]['test_failed'])

        execution_time, st_hour, starting_date= time_in_sec(results[each_results]['created_at'], results[each_results]['finished_at'])
        exec_time += execution_time
    return failure_list, exec_time, st_hour, starting_date

   ### Function to determine failure matrix element

In [47]:
def matrix_element(element):
    if element == 0:
        element = 1
    else:
        element = -1
    return element

### Writing failure matrix element and average execution time for each test case into csv file

In [48]:
length_list = []
output_file = input("Enter output filename: ")

with open(output_file+'.csv', 'w', newline='') as csv_file:
    fieldnames = ['Name', 'Duration','LastRun','E1', 'E2', 'E3','Hours']
    thewriter = csv.DictWriter(csv_file, fieldnames=fieldnames)
    thewriter.writeheader()

    for eachline in json_file:
            results = sorted(eachline['results'], key=lambda x: x['finished_at'])
            failure_list, exec_time, st_hour, starting_date = extract_information(results)

            if len(results)==max(length_list) and None not in failure_list:
                thewriter.writerow({'Name':eachline['id'], 
                                        "E1":matrix_element(failure_list[0]), 
                                        'E2':matrix_element(failure_list[1]), 
                                        'E3':matrix_element(failure_list[2]),
                                        "Duration": exec_time/len(results),
                                        "Hours":st_hour,
                                         "LastRun":starting_date})

Enter output filename:

In [49]:
df = pd.read_csv(output_file+'.csv')
df.head()

   Name     Duration     LastRun  E1  E2  E3  Hours
0  4134   537.666667  2015-02-06  -1  -1  -1     12
1   341   817.666667  2013-10-08  -1  -1  -1     14
2   348   509.666667  2015-02-06  -1  -1   1     12
3  1335   300.333333  2015-01-28   1   1   1     14
4  1515  1218.000000  2015-02-05  -1  -1  -1     18

In [50]:
def reverse_row_element(array_data):
    list_data = array_data.tolist()
    list_data.reverse()
    return list_data

# defining failure matrix MF
MF = df.loc[:,'E2':'E3'].values

rows = len(MF)
columns = len(MF[0])

#calculating distance of failure for each test cases
Verdict = []
i=0
for a, b in MF:
    i=i+1
    #print (a,b)
    if a==-1 and b==-1:
        Verdict.append(-1)
        
    elif a==1 and b==1:
        Verdict.append(1)
    elif a==-1 and b==1:
        Verdict.append(-1)
    elif a==1 and b==-1:
        Verdict.append(-1)
    else:
        print ("Nothing")
Verdict

[-1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1]

In [51]:
df['Verdict']=Verdict
df

     Name      Duration     LastRun  E1  E2  E3  Hours  Verdict
0    4134    537.666667  2015-02-06  -1  -1  -1     12       -1
1     341    817.666667  2013-10-08  -1  -1  -1     14       -1
2     348    509.666667  2015-02-06  -1  -1   1     12       -1
3    1335    300.333333  2015-01-28   1   1   1     14        1
4    1515   1218.000000  2015-02-05  -1  -1  -1     18       -1
..    ...           ...         ...  ..  ..  ..    ...      ...
284  4727   1440.333333  2014-05-05  -1  -1  -1     18       -1
285  2541   1080.666667  2015-02-04   1  -1   1      8       -1
286   352  11908.333333  2015-02-05  -1   1  -1     23       -1
287  9273    154.000000  2014-10-26  -1  -1  -1      7       -1
288  4097   2578.333333  2015-02-05   1   1   1     18        1

[289 rows x 8 columns]

In [52]:
length_list = []
output_file_2 = input("Enter output filename: ")

with open(output_file_2+'.csv', 'w', newline='') as csv_file:
    fieldnames = ['Name', 'Duration','LastRun','E1', 'E2', 'E3','Hours','Verdict']
    thewriter = csv.DictWriter(csv_file, fieldnames=fieldnames)
    thewriter.writeheader()

    for eachline in json_file_2:
            results = sorted(eachline['results'], key=lambda x: x['finished_at'])
            failure_list, exec_time, st_hour, starting_date = extract_information(results)

            if len(results)==max(length_list) and None not in failure_list:
                thewriter.writerow({'Name':eachline['id'], 
                                        "E1":matrix_element(failure_list[0]), 
                                        'E2':matrix_element(failure_list[1]), 
                                        'E3':matrix_element(failure_list[2]),
                                        'Verdict':matrix_element(failure_list[3]),
                                        "Duration": exec_time/len(results),
                                        "Hours":st_hour,
                                         "LastRun":starting_date})

Enter output filename:

In [53]:
df2 = pd.read_csv(output_file_2+'.csv')
df2

     Name  Duration     LastRun  E1  E2  E3  Hours  Verdict
0   18360    582.88  2017-02-23   1   1   1     18        1
1   18360    582.88  2017-02-23   1   1   1     18        1
2   18360    582.88  2017-02-23   1   1   1     18        1
3   18316    387.96  2017-02-23   1   1   1     18        1
4   18316    387.96  2017-02-23   1   1   1     18        1
..    ...       ...         ...  ..  ..  ..    ...      ...
62  16557    394.62  2017-02-23   1   1   1     18        1
63   1478    597.04  2017-02-23   1   1   1     19        1
64  16739    658.88  2017-02-23   1   1   1     18        1
65  13957    578.54  2017-02-23   1   1   1     18        1
66   7899    423.54  2017-02-23   1   1   1     19        1

[67 rows x 8 columns]

In [54]:
df.shape

(289, 8)

In [55]:
df2.shape

(67, 8)

In [56]:
# concat both dataframes
df_final = pd.concat([df, df2])

In [57]:
df_final.shape

(356, 8)

In [58]:
df_final.head()

   Name     Duration     LastRun  E1  E2  E3  Hours  Verdict
0  4134   537.666667  2015-02-06  -1  -1  -1     12       -1
1   341   817.666667  2013-10-08  -1  -1  -1     14       -1
2   348   509.666667  2015-02-06  -1  -1   1     12       -1
3  1335   300.333333  2015-01-28   1   1   1     14        1
4  1515  1218.000000  2015-02-05  -1  -1  -1     18       -1

### Implementing ROCKET algorithm to calculate priority value for each test case

In [59]:
#Preparing weights based on ROCKET algorithm
weights = np.array([0.00001,0.00002,0.00005])
MF = df_final.loc[:,'E1':'E3'].values

#Extracting average execution time from dataset
Te = df_final.Duration.values

#Calculating priority value for each test case
priority_value = (MF*weights).sum(axis=1)
priority_value+= Te/np.max(Te)/

### Adding new column DIST and CHANGE_IN_STATUS in the csv dataset

In [60]:

df_final['PRIORITY_VALUE'] = priority_value
#df_final.to_csv(output_file+'.csv', index = False)

In [61]:
df_final.head()

   Name     Duration     LastRun  E1  E2  E3  Hours  Verdict  PRIORITY_VALUE
0  4134   537.666667  2015-02-06  -1  -1  -1     12       -1      140.536188
1   341   817.666667  2013-10-08  -1  -1  -1     14       -1       92.411253
2   348   509.666667  2015-02-06  -1  -1   1     12       -1      148.257051
3  1335   300.333333  2015-01-28   1   1   1     14        1      251.592755
4  1515  1218.000000  2015-02-05  -1  -1  -1     18       -1       62.037413

### Algorithm to calculate distance from current execution

In [62]:
#function to reverse each row of the matrix
def reverse_row_element(array_data):
    list_data = array_data.tolist()
    list_data.reverse()
    return list_data

# defining failure matrix MF
MF = df_final.loc[:,'E1':'E3'].values

rows = len(MF)
columns = len(MF[0])

#calculating distance of failure for each test cases
distances_list = []

for i in range(rows):
    reversed_element = reverse_row_element(MF[i])
    if -1 in reversed_element:        
        for j in range(len(reversed_element)):
            if reversed_element[j] == -1:
                distances_list.insert(i, j+1)
                break
    else:
        #If distance == 0, means the test case has always been successful
        distances_list.insert(i, 0)

In [63]:
#calculating number of change of state of Pass/Fail for each test cases
change_in_status = []

for i in range(rows):
    each_element = MF[i]
    counter = 0
    for j in range(len(each_element)-1):
        if each_element[j]!=each_element[j+1]:
            counter+=1
    change_in_status.append(counter)

In [64]:
df_final['DIST']=distances_list
df_final['CHANGE_IN_STATUS']=change_in_status

In [65]:
df_final.shape

(356, 11)

In [66]:
#calculating cycle in each group
Hours = df_final.loc[:,'Hours'].values
Dates = df_final.loc[:,'LastRun'].values

cycle=[]
previous = 0
rows = len(Hours)
count=0
firsttime = False

for i in range(rows):
    #print (i)
    each_element =Hours[i]
    print ("Current :",each_element)
    print ("Previous :",previous)
    if i ==0:
        print ("nothing")
        count = count + 1

        previous = each_element
    
    
    
    if i >= 1:
        
        if each_element == previous:
            print ("True")
            if firsttime == False:
                firsttime = True
                count = count + 1
        else:
            previous = each_element
            firsttime = False

            count = count + 1
            print ("False")
     
    cycle.append(count)
    print ("Cycle :",count)
    print ('---')

Current : 12
Previous : 0
nothing
Cycle : 1
---
Current : 14
Previous : 12
False
Cycle : 2
---
Current : 12
Previous : 14
False
Cycle : 3
---
Current : 14
Previous : 12
False
Cycle : 4
---
Current : 18
Previous : 14
False
Cycle : 5
---
Current : 18
Previous : 18
True
Cycle : 6
---
Current : 18
Previous : 18
True
Cycle : 6
---
Current : 18
Previous : 18
True
Cycle : 6
---
Current : 18
Previous : 18
True
Cycle : 6
---
Current : 8
Previous : 18
False
Cycle : 7
---
Current : 10
Previous : 8
False
Cycle : 8
---
Current : 18
Previous : 10
False
Cycle : 9
---
Current : 18
Previous : 18
True
Cycle : 10
---
Current : 18
Previous : 18
True
Cycle : 10
---
Current : 18
Previous : 18
True
Cycle : 10
---
Current : 10
Previous : 18
False
Cycle : 11
---
Current : 0
Previous : 10
False
Cycle : 12
---
Current : 18
Previous : 0
False
Cycle : 13
---
Current : 5
Previous : 18
False
Cycle : 14
---
Current : 0
Previous : 5
False
Cycle : 15
---
Current : 18
Previous : 0
False
Cycle : 16
---
Current : 18
Previous : 18
True
Cycle : 17
---
Current : 18
Previous : 18
True
Cycle : 17
---
Current : 18
Previous : 18
True
Cycle : 17
---
Current : 18
Previous : 18
True
Cycle : 17
---
Current : 18
Previous : 18
True
Cycle : 17
---
Current : 18
Previous : 18
True
Cycle : 17
---
Current : 17
Previous : 18
False
Cycle : 18
---
Current : 18
Previous : 17
False
Cycle : 19
---
Current : 10
Previous : 18
False
Cycle : 20
---
Current : 18
Previous : 10
False
Cycle : 21
---
Current : 18
Previous : 18
True
Cycle : 22
---
Current : 18
Previous : 18
True
Cycle : 22
---
Current : 18
Previous : 18
True
Cycle : 22
---
Current : 18
Previous : 18
True
Cycle : 22
---
Current : 21
Previous : 18
False
Cycle : 23
---
Current : 21
Previous : 21
True
Cycle : 24
---
Current : 18
Previous : 21
False
Cycle : 25
---
Current : 18
Previous : 18
True
Cycle : 26
---
Current : 18
Previous : 18
True
Cycle : 26
---
Current : 18
Previous : 18
True
Cycle : 26
---
Current : 18
Previous : 18
True
Cycle : 26
---
Current : 18
Previous : 18
True
Cycle : 26
---
Current : 18
Previous : 18
True
Cycle : 26
---
Current : 12
Previous : 18
False
Cycle : 27
---
Current : 2
Previous : 12
False
Cycle : 28
---
Current : 18
Previous : 2
False
Cycle : 29
---
Current : 2
Previous : 18
False
Cycle : 30
---
Current : 0
Previous : 2
False
Cycle : 31
---
Current : 18
Previous : 0
False
Cycle : 32
---
Current : 13
Previous : 18
False
Cycle : 33
---
Current : 4
Previous : 13
False
Cycle : 34
---
Current : 4
Previous : 4
True
Cycle : 35
---
Current : 1
Previous : 4
False
Cycle : 36
---
Current : 1
Previous : 1
True
Cycle : 37
---
Current : 1
Previous : 1
True
Cycle : 37
---
Current : 1
Previous : 1
True
Cycle : 37
---
Current : 1
Previous : 1
True
Cycle : 37
---
Current : 1
Previous : 1
True
Cycle : 37
---
Current : 3
Previous : 1
False
Cycle : 38
---
Current : 1
Previous : 3
False
Cycle : 39
---
Current : 18
Previous : 1
False
Cycle : 40
---
Current : 4
Previous : 18
False
Cycle : 41
---
Current : 18
Previous : 4
False
Cycle : 42
---
Current : 13
Previous : 18
False
Cycle : 43
---
Current : 15
Previous : 13
False
Cycle : 44
---
Current : 15
Previous : 15
True
Cycle : 45
---
Current : 17
Previous : 15
False
Cycle : 46
---
Current : 14
Previous : 17
False
Cycle : 47
---
Current : 18
Previous : 14
False
Cycle : 48
---
Current : 18
Previous : 18
True
Cycle : 49
---
Current : 18
Previous : 18
True
Cycle : 49
---
Current : 11
Previous : 18
False
Cycle : 50
---
Current : 21
Previous : 11
False
Cycle : 51
---
Current : 21
Previous : 21
True
Cycle : 52
---
Current : 11
Previous : 21
False
Cycle : 53
---
Current : 11
Previous : 11
True
Cycle : 54
---
Current : 11
Previous : 11
True
Cycle : 54
---
Current : 11
Previous : 11
True
Cycle : 54
---
Current : 11
Previous : 11
True
Cycle : 54
---
Current : 11
Previous : 11
True
Cycle : 54
---
Current : 11
Previous : 11
True
Cycle : 54
---
Current : 11
Previous : 11
True
Cycle : 54
---
Current : 11
Previous : 11
True
Cycle : 54
---
Current : 11
Previous : 11
True
Cycle : 54
---
Current : 11
Previous : 11
True
Cycle : 54
---
Current : 11
Previous : 11
True
Cycle : 54
---
Current : 3
Previous : 11
False
Cycle : 55
---
Current : 9
Previous : 3
False
Cycle : 56
---
Current : 9
Previous : 9
True
Cycle : 57
---
Current : 11
Previous : 9
False
Cycle : 58
---
Current : 9
Previous : 11
False
Cycle : 59
---
Current : 9
Previous : 9
True
Cycle : 60
---
Current : 9
Previous : 9
True
Cycle : 60
---
Current : 14
Previous : 9
False
Cycle : 61
---
Current : 18
Previous : 14
False
Cycle : 62
---
Current : 18
Previous : 18
True
Cycle : 63
---
Current : 18
Previous : 18
True
Cycle : 63
---
Current : 18
Previous : 18
True
Cycle : 63
---
Current : 18
Previous : 18
True
Cycle : 63
---
Current : 18
Previous : 18
True
Cycle : 63
---
Current : 18
Previous : 18
True
Cycle : 63
---
Current : 18
Previous : 18
True
Cycle : 63
---
Current : 4
Previous : 18
False
Cycle : 64
---
Current : 4
Previous : 4
True
Cycle : 65
---
Current : 1
Previous : 4
False
Cycle : 66
---
Current : 1
Previous : 1
True
Cycle : 67
---
Current : 6
Previous : 1
False
Cycle : 68
---
Current : 18
Previous : 6
False
Cycle : 69
---
Current : 18
Previous : 18
True
Cycle : 70
---
Current : 18
Previous : 18
True
Cycle : 70
---
Current : 18
Previous : 18
True
Cycle : 70
---
Current : 22
Previous : 18
False
Cycle : 71
---
Current : 22
Previous : 22
True
Cycle : 72
---
Current : 4
Previous : 22
False
Cycle : 73
---
Current : 22
Previous : 4
False
Cycle : 74
---
Current : 22
Previous : 22
True
Cycle : 75
---
Current : 22
Previous : 22
True
Cycle : 75
---
Current : 10
Previous : 22
False
Cycle : 76
---
Current : 18
Previous : 10
False
Cycle : 77
---
Current : 5
Previous : 18
False
Cycle : 78
---
Current : 18
Previous : 5
False
Cycle : 79
---
Current : 18
Previous : 18
True
Cycle : 80
---
Current : 18
Previous : 18
True
Cycle : 80
---
Current : 18
Previous : 18
True
Cycle : 80
---
Current : 18
Previous : 18
True
Cycle : 80
---
Current : 18
Previous : 18
True
Cycle : 80
---
Current : 18
Previous : 18
True
Cycle : 80
---
Current : 18
Previous : 18
True
Cycle : 80
---
Current : 18
Previous : 18
True
Cycle : 80
---
Current : 18
Previous : 18
True
Cycle : 80
---
Current : 3
Previous : 18
False
Cycle : 81
---
Current : 3
Previous : 3
True
Cycle : 82
---
Current : 3
Previous : 3
True
Cycle : 82
---
Current : 3
Previous : 3
True
Cycle : 82
---
Current : 3
Previous : 3
True
Cycle : 82
---
Current : 20
Previous : 3
False
Cycle : 83
---
Current : 18
Previous : 20
False
Cycle : 84
---
Current : 17
Previous : 18
False
Cycle : 85
---
Current : 18
Previous : 17
False
Cycle : 86
---
Current : 18
Previous : 18
True
Cycle : 87
---
Current : 22
Previous : 18
False
Cycle : 88
---
Current : 18
Previous : 22
False
Cycle : 89
---
Current : 22
Previous : 18
False
Cycle : 90
---
Current : 18
Previous : 22
False
Cycle : 91
---
Current : 22
Previous : 18
False
Cycle : 92
---
Current : 12
Previous : 22
False
Cycle : 93
---
Current : 12
Previous : 12
True
Cycle : 94
---
Current : 11
Previous : 12
False
Cycle : 95
---
Current : 18
Previous : 11
False
Cycle : 96
---
Current : 18
Previous : 18
True
Cycle : 97
---
Current : 10
Previous : 18
False
Cycle : 98
---
Current : 18
Previous : 10
False
Cycle : 99
---
Current : 18
Previous : 18
True
Cycle : 100
---
Current : 18
Previous : 18
True
Cycle : 100
---
Current : 18
Previous : 18
True
Cycle : 100
---
Current : 1
Previous : 18
False
Cycle : 101
---
Current : 18
Previous : 1
False
Cycle : 102
---
Current : 15
Previous : 18
False
Cycle : 103
---
Current : 18
Previous : 15
False
Cycle : 104
---
Current : 18
Previous : 18
True
Cycle : 105
---
Current : 18
Previous : 18
True
Cycle : 105
---
Current : 12
Previous : 18
False
Cycle : 106
---
Current : 22
Previous : 12
False
Cycle : 107
---
Current : 18
Previous : 22
False
Cycle : 108
---
Current : 18
Previous : 18
True
Cycle : 109
---
Current : 18
Previous : 18
True
Cycle : 109
---
Current : 18
Previous : 18
True
Cycle : 109
---
Current : 18
Previous : 18
True
Cycle : 109
---
Current : 18
Previous : 18
True
Cycle : 109
---
Current : 18
Previous : 18
True
Cycle : 109
---
Current : 18
Previous : 18
True
Cycle : 109
---
Current : 10
Previous : 18
False
Cycle : 110
---
Current : 18
Previous : 10
False
Cycle : 111
---
Current : 18
Previous : 18
True
Cycle : 112
---
Current : 12
Previous : 18
False
Cycle : 113
---
Current : 12
Previous : 12
True
Cycle : 114
---
Current : 12
Previous : 12
True
Cycle : 114
---
Current : 12
Previous : 12
True
Cycle : 114
---
Current : 19
Previous : 12
False
Cycle : 115
---
Current : 19
Previous : 19
True
Cycle : 116
---
Current : 22
Previous : 19
False
Cycle : 117
---
Current : 19
Previous : 22
False
Cycle : 118
---
Current : 19
Previous : 19
True
Cycle : 119
---
Current : 9
Previous : 19
False
Cycle : 120
---
Current : 22
Previous : 9
False
Cycle : 121
---
Current : 19
Previous : 22
False
Cycle : 122
---
Current : 19
Previous : 19
True
Cycle : 123
---
Current : 19
Previous : 19
True
Cycle : 123
---
Current : 19
Previous : 19
True
Cycle : 123
---
Current : 19
Previous : 19
True
Cycle : 123
---
Current : 19
Previous : 19
True
Cycle : 123
---
Current : 19
Previous : 19
True
Cycle : 123
---
Current : 19
Previous : 19
True
Cycle : 123
---
Current : 19
Previous : 19
True
Cycle : 123
---
Current : 19
Previous : 19
True
Cycle : 123
---
Current : 20
Previous : 19
False
Cycle : 124
---
Current : 10
Previous : 20
False
Cycle : 125
---
Current : 19
Previous : 10
False
Cycle : 126
---
Current : 18
Previous : 19
False
Cycle : 127
---
Current : 18
Previous : 18
True
Cycle : 128
---
Current : 18
Previous : 18
True
Cycle : 128
---
Current : 18
Previous : 18
True
Cycle : 128
---
Current : 18
Previous : 18
True
Cycle : 128
---
Current : 18
Previous : 18
True
Cycle : 128
---
Current : 10
Previous : 18
False
Cycle : 129
---
Current : 13
Previous : 10
False
Cycle : 130
---
Current : 10
Previous : 13
False
Cycle : 131
---
Current : 15
Previous : 10
False
Cycle : 132
---
Current : 18
Previous : 15
False
Cycle : 133
---
Current : 18
Previous : 18
True
Cycle : 134
---
Current : 18
Previous : 18
True
Cycle : 134
---
Current : 18
Previous : 18
True
Cycle : 134
---
Current : 18
Previous : 18
True
Cycle : 134
---
Current : 1
Previous : 18
False
Cycle : 135
---
Current : 18
Previous : 1
False
Cycle : 136
---
Current : 18
Previous : 18
True
Cycle : 137
---
Current : 18
Previous : 18
True
Cycle : 137
---
Current : 18
Previous : 18
True
Cycle : 137
---
Current : 18
Previous : 18
True
Cycle : 137
---
Current : 18
Previous : 18
True
Cycle : 137
---
Current : 18
Previous : 18
True
Cycle : 137
---
Current : 18
Previous : 18
True
Cycle : 137
---
Current : 18
Previous : 18
True
Cycle : 137
---
Current : 18
Previous : 18
True
Cycle : 137
---
Current : 1
Previous : 18
False
Cycle : 138
---
Current : 15
Previous : 1
False
Cycle : 139
---
Current : 2
Previous : 15
False
Cycle : 140
---
Current : 9
Previous : 2
False
Cycle : 141
---
Current : 2
Previous : 9
False
Cycle : 142
---
Current : 18
Previous : 2
False
Cycle : 143
---
Current : 18
Previous : 18
True
Cycle : 144
---
Current : 18
Previous : 18
True
Cycle : 144
---
Current : 18
Previous : 18
True
Cycle : 144
---
Current : 5
Previous : 18
False
Cycle : 145
---
Current : 14
Previous : 5
False
Cycle : 146
---
Current : 18
Previous : 14
False
Cycle : 147
---
Current : 18
Previous : 18
True
Cycle : 148
---
Current : 14
Previous : 18
False
Cycle : 149
---
Current : 18
Previous : 14
False
Cycle : 150
---
Current : 18
Previous : 18
True
Cycle : 151
---
Current : 18
Previous : 18
True
Cycle : 151
---
Current : 18
Previous : 18
True
Cycle : 151
---
Current : 17
Previous : 18
False
Cycle : 152
---
Current : 18
Previous : 17
False
Cycle : 153
---
Current : 4
Previous : 18
False
Cycle : 154
---
Current : 4
Previous : 4
True
Cycle : 155
---
Current : 18
Previous : 4
False
Cycle : 156
---
Current : 18
Previous : 18
True
Cycle : 157
---
Current : 14
Previous : 18
False
Cycle : 158
---
Current : 1
Previous : 14
False
Cycle : 159
---
Current : 10
Previous : 1
False
Cycle : 160
---
Current : 12
Previous : 10
False
Cycle : 161
---
Current : 18
Previous : 12
False
Cycle : 162
---
Current : 12
Previous : 18
False
Cycle : 163
---
Current : 12
Previous : 12
True
Cycle : 164
---
Current : 12
Previous : 12
True
Cycle : 164
---
Current : 12
Previous : 12
True
Cycle : 164
---
Current : 12
Previous : 12
True
Cycle : 164
---
Current : 12
Previous : 12
True
Cycle : 164
---
Current : 12
Previous : 12
True
Cycle : 164
---
Current : 12
Previous : 12
True
Cycle : 164
---
Current : 12
Previous : 12
True
Cycle : 164
---
Current : 13
Previous : 12
False
Cycle : 165
---
Current : 13
Previous : 13
True
Cycle : 166
---
Current : 12
Previous : 13
False
Cycle : 167
---
Current : 22
Previous : 12
False
Cycle : 168
---
Current : 22
Previous : 22
True
Cycle : 169
---
Current : 11
Previous : 22
False
Cycle : 170
---
Current : 4
Previous : 11
False
Cycle : 171
---
Current : 18
Previous : 4
False
Cycle : 172
---
Current : 18
Previous : 18
True
Cycle : 173
---
Current : 16
Previous : 18
False
Cycle : 174
---
Current : 1
Previous : 16
False
Cycle : 175
---
Current : 22
Previous : 1
False
Cycle : 176
---
Current : 4
Previous : 22
False
Cycle : 177
---
Current : 4
Previous : 4
True
Cycle : 178
---
Current : 4
Previous : 4
True
Cycle : 178
---
Current : 4
Previous : 4
True
Cycle : 178
---
Current : 1
Previous : 4
False
Cycle : 179
---
Current : 22
Previous : 1
False
Cycle : 180
---
Current : 22
Previous : 22
True
Cycle : 181
---
Current : 22
Previous : 22
True
Cycle : 181
---
Current : 10
Previous : 22
False
Cycle : 182
---
Current : 18
Previous : 10
False
Cycle : 183
---
Current : 8
Previous : 18
False
Cycle : 184
---
Current : 23
Previous : 8
False
Cycle : 185
---
Current : 7
Previous : 23
False
Cycle : 186
---
Current : 18
Previous : 7
False
Cycle : 187
---
Current : 18
Previous : 18
True
Cycle : 188
---
Current : 18
Previous : 18
True
Cycle : 188
---
Current : 18
Previous : 18
True
Cycle : 188
---
Current : 18
Previous : 18
True
Cycle : 188
---
Current : 18
Previous : 18
True
Cycle : 188
---
Current : 18
Previous : 18
True
Cycle : 188
---
Current : 18
Previous : 18
True
Cycle : 188
---
Current : 18
Previous : 18
True
Cycle : 188
---
Current : 18
Previous : 18
True
Cycle : 188
---
Current : 19
Previous : 18
False
Cycle : 189
---
Current : 18
Previous : 19
False
Cycle : 190
---
Current : 18
Previous : 18
True
Cycle : 191
---
Current : 18
Previous : 18
True
Cycle : 191
---
Current : 19
Previous : 18
False
Cycle : 192
---
Current : 18
Previous : 19
False
Cycle : 193
---
Current : 18
Previous : 18
True
Cycle : 194
---
Current : 22
Previous : 18
False
Cycle : 195
---
Current : 22
Previous : 22
True
Cycle : 196
---
Current : 19
Previous : 22
False
Cycle : 197
---
Current : 18
Previous : 19
False
Cycle : 198
---
Current : 19
Previous : 18
False
Cycle : 199
---
Current : 18
Previous : 19
False
Cycle : 200
---
Current : 18
Previous : 18
True
Cycle : 201
---
Current : 18
Previous : 18
True
Cycle : 201
---
Current : 19
Previous : 18
False
Cycle : 202
---
Current : 18
Previous : 19
False
Cycle : 203
---
Current : 19
Previous : 18
False
Cycle : 204
---
Current : 18
Previous : 19
False
Cycle : 205
---
Current : 23
Previous : 18
False
Cycle : 206
---
Current : 23
Previous : 23
True
Cycle : 207
---
Current : 23
Previous : 23
True
Cycle : 207
---
Current : 23
Previous : 23
True
Cycle : 207
---
Current : 23
Previous : 23
True
Cycle : 207
---
Current : 18
Previous : 23
False
Cycle : 208
---
Current : 18
Previous : 18
True
Cycle : 209
---
Current : 18
Previous : 18
True
Cycle : 209
---
Current : 18
Previous : 18
True
Cycle : 209
---
Current : 18
Previous : 18
True
Cycle : 209
---
Current : 18
Previous : 18
True
Cycle : 209
---
Current : 23
Previous : 18
False
Cycle : 210
---
Current : 23
Previous : 23
True
Cycle : 211
---
Current : 19
Previous : 23
False
Cycle : 212
---
Current : 18
Previous : 19
False
Cycle : 213
---
Current : 19
Previous : 18
False
Cycle : 214
---
Current : 18
Previous : 19
False
Cycle : 215
---
Current : 23
Previous : 18
False
Cycle : 216
---
Current : 18
Previous : 23
False
Cycle : 217
---
Current : 23
Previous : 18
False
Cycle : 218
---

Current : 18
Previous : 23
False
Cycle : 219
---
Current : 18
Previous : 18
True
Cycle : 220
---
Current : 18
Previous : 18
True
Cycle : 220
---
Current : 19
Previous : 18
False
Cycle : 221
---
Current : 23
Previous : 19
False
Cycle : 222
---
Current : 18
Previous : 23
False
Cycle : 223
---
Current : 18
Previous : 18
True
Cycle : 224
---
Current : 18
Previous : 18
True
Cycle : 224
---
Current : 18
Previous : 18
True
Cycle : 224
---
Current : 23
Previous : 18
False
Cycle : 225
---
Current : 23
Previous : 23
True
Cycle : 226
---
Current : 23
Previous : 23
True
Cycle : 226
---
Current : 18
Previous : 23
False
Cycle : 227
---
Current : 18
Previous : 18
True
Cycle : 228
---
Current : 18
Previous : 18
True
Cycle : 228
---
Current : 19
Previous : 18
False
Cycle : 229
---
Current : 18
Previous : 19
False
Cycle : 230
---
Current : 18
Previous : 18
True
Cycle : 231
---
Current : 19
Previous : 18
False
Cycle : 232
---

In [67]:
len(df_final)

356

In [68]:
df_final['Cycle'] = cycle
df_final.head()

,Name,Duration,LastRun,E1,E2,E3,Hours,Verdict,PRIORITY_VALUE,DIST,CHANGE_IN_STATUS,Cycle
0,4134,537.666667,2015-02-06,-1,-1,-1,12,-1,140.536188,1,0,1
1,341,817.666667,2013-10-08,-1,-1,-1,14,-1,92.411253,1,0,2
2,348,509.666667,2015-02-06,-1,-1,1,12,-1,148.257051,2,1,3
3,1335,300.333333,2015-01-28,1,1,1,14,1,251.592755,0,0,4
4,1515,1218.000000,2015-02-05,-1,-1,-1,18,-1,62.037413,1,0,5

In [69]:
# Update Dates based on cycles

from datetime import timedelta


from datetime import datetime
Month_of_thirty_days = [2,4,6,9,11]
from dateutil.relativedelta import relativedelta

currentDay = datetime.now().day
currentMonth = datetime.now().month
currentYear = datetime.now().year


Hours = df_final.loc[:,'Hours'].values
Dates = df_final.loc[:,'LastRun'].values

previous = 0
rows = len(Hours)
count=0
firsttime = False


# for rest of the cycle
for i in range(rows):
    each_element =cycle[i]
    print ("Cycle :",each_element)
    print (Dates[i])
    if i==0:
        print ("nothing")
        
    if i >= 1:
        datestring = Dates[i]
        
        dt = datetime.strptime(datestring, '%Y-%m-%d')
 
        value = each_element-1
        # print (timedelta(days=value))
        dtt =  dt + timedelta(days=value)
        Dates[i] =  str(dtt.year) +"-"+ str(dtt.month) +"-"+ str(dtt.day)
    print (Dates[i])
    print ('---')

Cycle : 1
2015-02-06
nothing
2015-02-06
---
Cycle : 2
2013-10-08
2013-10-9
---
Cycle : 3
2015-02-06
2015-2-8
---
Cycle : 4
2015-01-28
2015-1-31
---
Cycle : 5
2015-02-05
2015-2-9
---
Cycle : 6
2015-02-05
2015-2-10
---
Cycle : 6
2015-02-05
2015-2-10
---
Cycle : 6
2015-02-05
2015-2-10
---
Cycle : 6
2014-11-09
2014-11-14
---
Cycle : 7
2014-02-26
2014-3-4
---
Cycle : 8
2015-01-14
2015-1-21
---
Cycle : 9
2015-02-05
2015-2-13
---
Cycle : 10
2015-02-05
2015-2-14
---
Cycle : 10
2015-02-05
2015-2-14
---
Cycle : 10
2015-02-05
2015-2-14
---
Cycle : 11
2015-02-06
2015-2-16
---
Cycle : 12
2014-11-14
2014-11-25
---
Cycle : 13
2015-02-05
2015-2-17
---
Cycle : 14
2014-05-21
2014-6-3
---
Cycle : 15
2015-02-06
2015-2-20
---
Cycle : 16
2015-02-05
2015-2-20
---
Cycle : 17
2015-02-05
2015-2-21
---
Cycle : 17
2015-02-05
2015-2-21
---
Cycle : 17
2015-02-05
2015-2-21
---
Cycle : 17
2015-02-05
2015-2-21
---
Cycle : 17
2015-02-05
2015-2-21
---
Cycle : 17
2015-02-05
2015-2-21
---
Cycle : 18
2015-02-04
2015-2-21
---
Cycle : 19
2015-02-05
2015-2-23
---
Cycle : 20
2015-01-14
2015-2-2
---
Cycle : 21
2015-02-05
2015-2-25
---
Cycle : 22
2015-02-05
2015-2-26
---
Cycle : 22
2015-02-05
2015-2-26
---
Cycle : 22
2015-02-05
2015-2-26
---
Cycle : 22
2015-02-05
2015-2-26
---
Cycle : 23
2014-11-17
2014-12-9
---
Cycle : 24
2014-11-14
2014-12-7
---
Cycle : 25
2015-02-05
2015-3-1
---
Cycle : 26
2015-02-05
2015-3-2
---
Cycle : 26
2015-02-05
2015-3-2
---
Cycle : 26
2014-11-07
2014-12-2
---
Cycle : 26
2015-02-05
2015-3-2
---
Cycle : 26
2015-02-05
2015-3-2
---
Cycle : 26
2015-02-05
2015-3-2
---
Cycle : 27
2015-02-06
2015-3-4
---
Cycle : 28
2014-08-22
2014-9-18
---
Cycle : 29
2015-01-16
2015-2-13
---
Cycle : 30
2014-08-22
2014-9-20
---
Cycle : 31
2014-09-03
2014-10-3
---
Cycle : 32
2015-02-05
2015-3-8
---
Cycle : 33
2015-02-06
2015-3-10
---
Cycle : 34
2015-02-06
2015-3-11
---
Cycle : 35
2015-02-06
2015-3-12
---
Cycle : 36
2015-02-06
2015-3-13
---
Cycle : 37
2015-02-06
2015-3-14
---
Cycle : 37
2015-02-06
2015-3-14
---
Cycle : 37
2014-12-18
2015-1-23
---
Cycle : 37
2014-11-13
2014-12-19
---
Cycle : 37
2014-12-18
2015-1-23
---
Cycle : 38
2014-09-08
2014-10-15
---
Cycle : 39
2015-02-06
2015-3-16
---
Cycle : 40
2015-02-05
2015-3-16
---
Cycle : 41
2015-01-27
2015-3-8
---
Cycle : 42
2015-02-05
2015-3-18
---
Cycle : 43
2015-02-05
2015-3-19
---
Cycle : 44
2015-01-28
2015-3-12
---
Cycle : 45
2015-01-28
2015-3-13
---
Cycle : 46
2015-02-05
2015-3-22
---
Cycle : 47
2015-01-22
2015-3-9
---
Cycle : 48
2015-02-05
2015-3-24
---
Cycle : 49
2015-02-05
2015-3-25
---
Cycle : 49
2015-02-05
2015-3-25
---
Cycle : 50
2014-04-02
2014-5-21
---
Cycle : 51
2014-11-25
2015-1-14
---
Cycle : 52
2014-11-25
2015-1-15
---
Cycle : 53
2015-02-06
2015-3-30
---
Cycle : 54
2015-02-06
2015-3-31
---
Cycle : 54
2015-02-06
2015-3-31
---
Cycle : 54
2015-02-06
2015-3-31
---
Cycle : 54
2015-02-06
2015-3-31
---
Cycle : 54
2015-02-06
2015-3-31
---
Cycle : 54
2015-02-06
2015-3-31
---
Cycle : 54
2014-11-06
2014-12-29
---
Cycle : 54
2015-02-06
2015-3-31
---
Cycle : 54
2014-11-06
2014-12-29
---
Cycle : 54
2015-02-06
2015-3-31
---
Cycle : 54
2015-02-06
2015-3-31
---
Cycle : 55
2015-02-06
2015-4-1
---
Cycle : 56
2014-03-10
2014-5-4
---
Cycle : 57
2014-03-10
2014-5-5
---
Cycle : 58
2014-03-11
2014-5-7
---
Cycle : 59
2014-03-10
2014-5-7
---
Cycle : 60
2014-03-10
2014-5-8
---
Cycle : 60
2014-05-06
2014-7-4
---
Cycle : 61
2015-02-06
2015-4-7
---
Cycle : 62
2015-02-05
2015-4-7
---
Cycle : 63
2015-02-05
2015-4-8
---
Cycle : 63
2015-02-05
2015-4-8
---
Cycle : 63
2015-02-05
2015-4-8
---
Cycle : 63
2015-02-05
2015-4-8
---
Cycle : 63
2015-02-05
2015-4-8
---
Cycle : 63
2015-02-05
2015-4-8
---
Cycle : 63
2015-02-05
2015-4-8
---
Cycle : 64
2015-02-06
2015-4-10
---
Cycle : 65
2015-02-06
2015-4-11
---
Cycle : 66
2015-02-06
2015-4-12
---
Cycle : 67
2015-02-06
2015-4-13
---
Cycle : 68
2015-02-06
2015-4-14
---
Cycle : 69
2015-02-05
2015-4-14
---
Cycle : 70
2015-02-05
2015-4-15
---
Cycle : 70
2015-02-05
2015-4-15
---
Cycle : 70
2015-02-05
2015-4-15
---
Cycle : 71
2015-01-31
2015-4-11
---
Cycle : 72
2015-01-31
2015-4-12
---
Cycle : 73
2014-08-07
2014-10-18
---
Cycle : 74
2015-01-31
2015-4-14
---
Cycle : 75
2015-01-31
2015-4-15
---
Cycle : 75
2015-01-31
2015-4-15
---
Cycle : 76
2015-02-06
2015-4-22
---
Cycle : 77
2014-09-25
2014-12-10
---
Cycle : 78
2013-09-11
2013-11-27
---
Cycle : 79
2015-02-05
2015-4-24
---
Cycle : 80
2015-02-05
2015-4-25
---
Cycle : 80
2015-02-05
2015-4-25
---
Cycle : 80
2015-02-05
2015-4-25
---
Cycle : 80
2015-02-05
2015-4-25
---
Cycle : 80
2015-02-05
2015-4-25
---
Cycle : 80
2015-02-05
2015-4-25
---
Cycle : 80
2015-02-05
2015-4-25
---
Cycle : 80
2015-02-05
2015-4-25
---
Cycle : 80
2014-10-24
2015-1-11
---
Cycle : 81
2014-06-24
2014-9-12
---
Cycle : 82
2014-06-24
2014-9-13
---
Cycle : 82
2014-06-24
2014-9-13
---
Cycle : 82
2014-06-24
2014-9-13
---
Cycle : 82
2014-06-24
2014-9-13
---
Cycle : 83
2014-09-02
2014-11-23
---
Cycle : 84
2015-02-05
2015-4-29
---
Cycle : 85
2014-06-10
2014-9-2
---
Cycle : 86
2015-02-05
2015-5-1
---
Cycle : 87
2015-02-05
2015-5-2
---
Cycle : 88
2015-01-31
2015-4-28
---
Cycle : 89
2015-02-05
2015-5-4
---
Cycle : 90
2015-01-31
2015-4-30
---
Cycle : 91
2015-02-04
2015-5-5
---
Cycle : 92
2015-01-31
2015-5-2
---
Cycle : 93
2015-02-06
2015-5-9
---
Cycle : 94
2015-02-06
2015-5-10
---
Cycle : 95
2015-02-06
2015-5-11
---
Cycle : 96
2015-01-29
2015-5-4
---
Cycle : 97
2015-01-29
2015-5-5
---
Cycle : 98
2014-12-18
2015-3-25
---
Cycle : 99
2015-02-05
2015-5-14
---
Cycle : 100
2015-02-05
2015-5-15
---
Cycle : 100
2015-02-05
2015-5-15
---
Cycle : 100
2015-02-05
2015-5-15
---
Cycle : 101
2015-02-06
2015-5-17
---
Cycle : 102
2015-02-05
2015-5-17
---
Cycle : 103
2014-08-07
2014-11-17
---
Cycle : 104
2015-02-05
2015-5-19
---
Cycle : 105
2015-02-05
2015-5-20
---
Cycle : 105
2015-02-05
2015-5-20
---
Cycle : 106
2015-02-06
2015-5-22
---
Cycle : 107
2015-01-31
2015-5-17
---
Cycle : 108
2015-02-05
2015-5-23
---
Cycle : 109
2014-10-30
2015-2-15
---
Cycle : 109
2015-02-05
2015-5-24
---
Cycle : 109
2015-02-05
2015-5-24
---
Cycle : 109
2015-02-05
2015-5-24
---
Cycle : 109
2015-02-05
2015-5-24
---
Cycle : 109
2015-02-05
2015-5-24
---
Cycle : 109
2015-02-02
2015-5-21
---
Cycle : 110
2015-02-03
2015-5-23
---
Cycle : 111
2015-02-05
2015-5-26
---
Cycle : 112
2015-02-05
2015-5-27
---
Cycle : 113
2014-08-25
2014-12-15
---
Cycle : 114
2014-08-25
2014-12-16
---
Cycle : 114
2014-08-25
2014-12-16
---
Cycle : 114
2014-08-25
2014-12-16
---
Cycle : 115
2015-02-05
2015-5-30
---
Cycle : 116
2015-02-05
2015-5-31
---
Cycle : 117
2015-02-05
2015-6-1
---
Cycle : 118
2015-02-05
2015-6-2
---
Cycle : 119
2015-02-05
2015-6-3
---
Cycle : 120
2015-02-06
2015-6-5
---
Cycle : 121
2015-02-05
2015-6-5
---
Cycle : 122
2015-02-05
2015-6-6
---
Cycle : 123
2015-02-05
2015-6-7
---
Cycle : 123
2015-02-05
2015-6-7
---
Cycle : 123
2015-02-05
2015-6-7
---
Cycle : 123
2015-02-05
2015-6-7
---
Cycle : 123
2015-02-05
2015-6-7
---
Cycle : 123
2015-02-05
2015-6-7
---
Cycle : 123
2015-02-05
2015-6-7
---
Cycle : 123
2015-02-05
2015-6-7
---
Cycle : 123
2015-02-05
2015-6-7
---
Cycle : 124
2015-02-02
2015-6-5
---
Cycle : 125
2015-02-05
2015-6-9
---
Cycle : 126
2015-02-02
2015-6-7
---
Cycle : 127
2015-02-05
2015-6-11
---
Cycle : 128
2015-02-05
2015-6-12
---
Cycle : 128
2015-02-05
2015-6-12
---
Cycle : 128
2015-02-05
2015-6-12
---
Cycle : 128
2015-02-05
2015-6-12
---
Cycle : 128
2015-02-05
2015-6-12
---
Cycle : 129
2015-01-14
2015-5-22
---
Cycle : 130
2014-06-05
2014-10-12
---
Cycle : 131
2015-01-14
2015-5-24
---
Cycle : 132
2014-06-23
2014-11-1
---
Cycle : 133
2015-02-05
2015-6-17
---
Cycle : 134
2015-02-05
2015-6-18
---
Cycle : 134
2015-02-05
2015-6-18
---
Cycle : 134
2015-02-05
2015-6-18
---
Cycle : 134
2015-02-05
2015-6-18
---
Cycle : 135
2015-02-06
2015-6-20
---
Cycle : 136
2014-10-20
2015-3-4
---
Cycle : 137
2014-10-20
2015-3-5
---
Cycle : 137
2014-10-20
2015-3-5
---
Cycle : 137
2014-10-20
2015-3-5
---
Cycle : 137
2014-11-07
2015-3-23
---
Cycle : 137
2014-11-07
2015-3-23
---
Cycle : 137
2015-02-05
2015-6-21
---
Cycle : 137
2015-02-05
2015-6-21
---
Cycle : 137
2015-02-05
2015-6-21
---
Cycle : 137
2015-02-05
2015-6-21
---
Cycle : 138
2015-02-06
2015-6-23
---
Cycle : 139
2014-11-24
2015-4-11
---
Cycle : 140
2014-11-10
2015-3-29
---
Cycle : 141
2014-11-25
2015-4-14
---
Cycle : 142
2014-11-10
2015-3-31
---
Cycle : 143
2014-12-08
2015-4-29
---
Cycle : 144
2015-02-05
2015-6-28
---
Cycle : 144
2015-02-05
2015-6-28
---
Cycle : 144
2015-02-05
2015-6-28
---
Cycle : 145
2014-03-26
2014-8-17
---
Cycle : 146
2015-02-06
2015-7-1
---
Cycle : 147
2015-02-05
2015-7-1
---
Cycle : 148
2015-02-05
2015-7-2
---
Cycle : 149
2014-11-19
2015-4-16
---
Cycle : 150
2015-02-05
2015-7-4
---
Cycle : 151
2014-01-05
2014-6-4
---
Cycle : 151
2014-01-05
2014-6-4
---
Cycle : 151
2014-01-05
2014-6-4
---
Cycle : 152
2014-01-05
2014-6-5
---
Cycle : 153
2015-02-05
2015-7-7
---
Cycle : 154
2015-02-06
2015-7-9
---
Cycle : 155
2015-02-06
2015-7-10
---
Cycle : 156
2014-11-20
2015-4-24
---
Cycle : 157
2015-02-05
2015-7-11
---
Cycle : 158
2015-02-06
2015-7-13
---
Cycle : 159
2015-02-06
2015-7-14
---
Cycle : 160
2015-02-06
2015-7-15
---
Cycle : 161
2015-02-06
2015-7-16
---
Cycle : 162
2015-01-29
2015-7-9
---
Cycle : 163
2015-02-06
2015-7-18
---
Cycle : 164
2015-02-06
2015-7-19
---
Cycle : 164
2015-02-06
2015-7-19
---
Cycle : 164
2015-02-06
2015-7-19
---
Cycle : 164
2015-01-09
2015-6-21
---
Cycle : 164
2015-02-06
2015-7-19
---
Cycle : 164
2015-02-06
2015-7-19
---
Cycle : 164
2015-02-06
2015-7-19
---
Cycle : 164
2015-02-06
2015-7-19
---
Cycle : 165
2015-02-06
2015-7-20
---
Cycle : 166
2015-02-06
2015-7-21
---
Cycle : 167
2015-02-06
2015-7-22
---
Cycle : 168
2015-01-31
2015-7-17
---
Cycle : 169
2015-01-31
2015-7-18
---
Cycle : 170
2015-02-06
2015-7-25
---
Cycle : 171
2015-02-06
2015-7-26
---
Cycle : 172
2015-02-05
2015-7-26
---
Cycle : 173
2015-02-05
2015-7-27
---
Cycle : 174
2014-11-11
2015-5-3
---
Cycle : 175
2015-02-06
2015-7-30
---
Cycle : 176
2015-01-31
2015-7-25
---
Cycle : 177
2015-02-06
2015-8-1
---
Cycle : 178
2015-02-06
2015-8-2
---
Cycle : 178
2015-02-01
2015-7-28
---
Cycle : 178
2015-02-01
2015-7-28
---
Cycle : 179
2015-02-06
2015-8-3
---
Cycle : 180
2015-01-31
2015-7-29
---
Cycle : 181
2015-01-31
2015-7-30
---
Cycle : 181
2015-01-31
2015-7-30
---
Cycle : 182
2015-01-14
2015-7-14
---
Cycle : 183
2014-05-05
2014-11-3
---
Cycle : 184
2015-02-04
2015-8-6
---
Cycle : 185
2015-02-05
2015-8-8
---
Cycle : 186
2014-10-26
2015-4-29
---
Cycle : 187
2015-02-05
2015-8-10
---
Cycle : 188
2017-02-23
2017-8-29
---
Cycle : 188
2017-02-23
2017-8-29
---
Cycle : 188
2017-02-23
2017-8-29
---
Cycle : 188
2017-02-23
2017-8-29
---
Cycle : 188
2017-02-23
2017-8-29
---
Cycle : 188
2017-02-23
2017-8-29
---
Cycle : 188
2017-02-23
2017-8-29
---
Cycle : 188
2017-02-23
2017-8-29
---
Cycle : 188
2017-02-23
2017-8-29
---
Cycle : 189
2017-02-23
2017-8-30
---
Cycle : 190
2017-02-23
2017-8-31
---
Cycle : 191
2017-02-23
2017-9-1
---
Cycle : 191
2017-02-23
2017-9-1
---
Cycle : 192
2017-02-23
2017-9-2
---
Cycle : 193
2017-02-23
2017-9-3
---
Cycle : 194
2017-02-23
2017-9-4
---
Cycle : 195
2017-02-23
2017-9-5
---
Cycle : 196
2017-02-23
2017-9-6
---
Cycle : 197
2017-02-23
2017-9-7
---
Cycle : 198
2017-02-23
2017-9-8
---
Cycle : 199
2017-02-23
2017-9-9
---
Cycle : 200
2017-02-23
2017-9-10
---
Cycle : 201
2017-02-23
2017-9-11
---
Cycle : 201
2017-02-23
2017-9-11
---
Cycle : 202
2017-02-23
2017-9-12
---
Cycle : 203
2017-02-23
2017-9-13
---
Cycle : 204
2017-02-23
2017-9-14
---
Cycle : 205
2017-02-23
2017-9-15
---
Cycle : 206
2017-02-23
2017-9-16
---
Cycle : 207
2017-02-23
2017-9-17
---
Cycle : 207
2017-02-23
2017-9-17
---
Cycle : 207
2017-02-23
2017-9-17
---
Cycle : 207
2017-02-23
2017-9-17
---
Cycle : 208
2017-02-23
2017-9-18
---
Cycle : 209
2017-02-23
2017-9-19
---
Cycle : 209
2017-02-23
2017-9-19
---
Cycle : 209
2017-02-23
2017-9-19
---
Cycle : 209
2017-02-23
2017-9-19
---
Cycle : 209
2017-02-23
2017-9-19
---
Cycle : 210
2017-02-23
2017-9-20
---
Cycle : 211
2017-02-23
2017-9-21
---
Cycle : 212
2017-02-23
2017-9-22
---
Cycle : 213
2017-02-23
2017-9-23
---
Cycle : 214
2017-02-23
2017-9-24
---
Cycle : 215
2017-02-23
2017-9-25
---
Cycle : 216
2017-02-23
2017-9-26
---
Cycle : 217
2017-02-23
2017-9-27
---
Cycle : 218
2017-02-23
2017-9-28
---
Cycle : 219
2017-02-23
2017-9-29
---
Cycle : 220
2017-02-23
2017-9-30
---
Cycle : 220
2017-02-23
2017-9-30
---
Cycle : 221
2017-02-23
2017-10-1
---
Cycle : 222
2017-02-23
2017-10-2
---
Cycle : 223
2017-02-23
2017-10-3
---
Cycle : 224
2017-02-23
2017-10-4
---
Cycle : 224
2017-02-23
2017-10-4
---
Cycle : 224
2017-02-23
2017-10-4
---
Cycle : 225
2017-02-23
2017-10-5
---
Cycle : 226
2017-02-23
2017-10-6
---
Cycle : 226
2017-02-23
2017-10-6
---
Cycle : 227
2017-02-23
2017-10-7
---
Cycle : 228
2017-02-23
2017-10-8
---
Cycle : 228
2017-02-23
2017-10-8
---
Cycle : 229
2017-02-23
2017-10-9
---
Cycle : 230
2017-02-23
2017-10-10
---
Cycle : 231
2017-02-23
2017-10-11
---
Cycle : 232
2017-02-23
2017-10-12
---

In [ ]:
#for 1st Cycle
from datetime import datetime
datestring = Dates[0]
dt = datetime.strptime(datestring, '%Y-%m-%d')
#print (dt.year, dt.month, dt.day)

from datetime import date
f_date = date(dt.year, dt.month, dt.day)
l_date = date(currentYear,currentMonth,currentDay)
delta = l_date - f_date

print(delta.days)
days.append(delta.days)

In [70]:
# claculating difference in days among test cases using LastRun column

from datetime import datetime
Month_of_thirty_days = [2,4,6,9,11]
from dateutil.relativedelta import relativedelta

currentDay = datetime.now().day
currentMonth = datetime.now().month
currentYear = datetime.now().year


days=[]
previous = 0
rows = len(Dates)
count=0
firsttime = False
'''
#for 1st Cycle
from datetime import datetime
datestring = Dates[0]
dt = datetime.strptime(datestring, '%Y-%m-%d')
#print (dt.year, dt.month, dt.day)

from datetime import date
f_date = date(dt.year, dt.month, dt.day)
l_date = date(currentYear,currentMonth,currentDay)
delta = l_date - f_date
print(delta.days)
days.append(delta.days)
'''



# for rest of the cycle
for i in range(rows):
    each_element =cycle[i]
    print ("Cycle :",each_element)
    
    
    
    if i ==0:
        #print ("1st Cycle")
        #for 1st Cycle
        from datetime import datetime
        datestring = Dates[i]

        dt = datetime.strptime(datestring, '%Y-%m-%d')

        f_date = date(dt.year, dt.month, dt.day)
        l_date = date(currentYear,currentMonth,currentDay)
        delta = l_date - f_date
        print (delta)
        print (currentYear, currentMonth, currentDay, " - ", dt.year, dt.month, dt.day)

        previous = each_element
        
    if i >= 1:
        datestring = Dates[i]
        datestring_prev = Dates[i-1]
        dt = datetime.strptime(datestring, '%Y-%m-%d')
        dt_prev = datetime.strptime(datestring_prev, '%Y-%m-%d')


        f_date = date(dt.year, dt.month, dt.day)
        l_date = date(dt_prev.year, dt_prev.month, dt_prev.day)
        delta = l_date - f_date
        print ("** ",dt_prev.year, dt_prev.month, dt_prev.day, " - ", dt.year, dt.month, dt.day)
        

    days.append(delta.days)
 
    print ('---')

Cycle : 1
2075 days, 0:00:00
2020 10 12  -  2015 2 6
---
Cycle : 2
**  2015 2 6  -  2013 10 9
---
Cycle : 3
**  2013 10 9  -  2015 2 8
---
Cycle : 4
**  2015 2 8  -  2015 1 31
---
Cycle : 5
**  2015 1 31  -  2015 2 9
---
Cycle : 6
**  2015 2 9  -  2015 2 10
---
Cycle : 6
**  2015 2 10  -  2015 2 10
---
Cycle : 6
**  2015 2 10  -  2015 2 10
---
Cycle : 6
**  2015 2 10  -  2014 11 14
---
Cycle : 7
**  2014 11 14  -  2014 3 4
---
Cycle : 8
**  2014 3 4  -  2015 1 21
---
Cycle : 9
**  2015 1 21  -  2015 2 13
---
Cycle : 10
**  2015 2 13  -  2015 2 14
---
Cycle : 10
**  2015 2 14  -  2015 2 14
---
Cycle : 10
**  2015 2 14  -  2015 2 14
---
Cycle : 11
**  2015 2 14  -  2015 2 16
---
Cycle : 12
**  2015 2 16  -  2014 11 25
---
Cycle : 13
**  2014 11 25  -  2015 2 17
---
Cycle : 14
**  2015 2 17  -  2014 6 3
---
Cycle : 15
**  2014 6 3  -  2015 2 20
---
Cycle : 16
**  2015 2 20  -  2015 2 20
---
Cycle : 17
**  2015 2 20  -  2015 2 21
---
Cycle : 17
**  2015 2 21  -  2015 2 21
---
Cycle : 17
**  2015 2 21  -  2015 2 21
---
Cycle : 17
**  2015 2 21  -  2015 2 21
---
Cycle : 17
**  2015 2 21  -  2015 2 21
---
Cycle : 17
**  2015 2 21  -  2015 2 21
---
Cycle : 18
**  2015 2 21  -  2015 2 21
---
Cycle : 19
**  2015 2 21  -  2015 2 23
---
Cycle : 20
**  2015 2 23  -  2015 2 2
---
Cycle : 21
**  2015 2 2  -  2015 2 25
---
Cycle : 22
**  2015 2 25  -  2015 2 26
---
Cycle : 22
**  2015 2 26  -  2015 2 26
---
Cycle : 22
**  2015 2 26  -  2015 2 26
---
Cycle : 22
**  2015 2 26  -  2015 2 26
---
Cycle : 23
**  2015 2 26  -  2014 12 9
---
Cycle : 24
**  2014 12 9  -  2014 12 7
---
Cycle : 25
**  2014 12 7  -  2015 3 1
---
Cycle : 26
**  2015 3 1  -  2015 3 2
---
Cycle : 26
**  2015 3 2  -  2015 3 2
---
Cycle : 26
**  2015 3 2  -  2014 12 2
---
Cycle : 26
**  2014 12 2  -  2015 3 2
---
Cycle : 26
**  2015 3 2  -  2015 3 2
---
Cycle : 26
**  2015 3 2  -  2015 3 2
---
Cycle : 27
**  2015 3 2  -  2015 3 4
---
Cycle : 28
**  2015 3 4  -  2014 9 18
---
Cycle : 29
**  2014 9 18  -  2015 2 13
---
Cycle : 30
**  2015 2 13  -  2014 9 20
---
Cycle : 31
**  2014 9 20  -  2014 10 3
---
Cycle : 32
**  2014 10 3  -  2015 3 8
---
Cycle : 33
**  2015 3 8  -  2015 3 10
---
Cycle : 34
**  2015 3 10  -  2015 3 11
---
Cycle : 35
**  2015 3 11  -  2015 3 12
---
Cycle : 36
**  2015 3 12  -  2015 3 13
---
Cycle : 37
**  2015 3 13  -  2015 3 14
---
Cycle : 37
**  2015 3 14  -  2015 3 14
---
Cycle : 37
**  2015 3 14  -  2015 1 23
---
Cycle : 37
**  2015 1 23  -  2014 12 19
---
Cycle : 37
**  2014 12 19  -  2015 1 23
---
Cycle : 38
**  2015 1 23  -  2014 10 15
---
Cycle : 39
**  2014 10 15  -  2015 3 16
---
Cycle : 40
**  2015 3 16  -  2015 3 16
---
Cycle : 41
**  2015 3 16  -  2015 3 8
---
Cycle : 42
**  2015 3 8  -  2015 3 18
---
Cycle : 43
**  2015 3 18  -  2015 3 19
---
Cycle : 44
**  2015 3 19  -  2015 3 12
---
Cycle : 45
**  2015 3 12  -  2015 3 13
---
Cycle : 46
**  2015 3 13  -  2015 3 22
---
Cycle : 47
**  2015 3 22  -  2015 3 9
---
Cycle : 48
**  2015 3 9  -  2015 3 24
---
Cycle : 49
**  2015 3 24  -  2015 3 25
---
Cycle : 49
**  2015 3 25  -  2015 3 25
---
Cycle : 50
**  2015 3 25  -  2014 5 21
---
Cycle : 51
**  2014 5 21  -  2015 1 14
---
Cycle : 52
**  2015 1 14  -  2015 1 15
---
Cycle : 53
**  2015 1 15  -  2015 3 30
---
Cycle : 54
**  2015 3 30  -  2015 3 31
---
Cycle : 54
**  2015 3 31  -  2015 3 31
---
Cycle : 54
**  2015 3 31  -  2015 3 31
---
Cycle : 54
**  2015 3 31  -  2015 3 31
---
Cycle : 54
**  2015 3 31  -  2015 3 31
---
Cycle : 54
**  2015 3 31  -  2015 3 31
---
Cycle : 54
**  2015 3 31  -  2014 12 29
---
Cycle : 54
**  2014 12 29  -  2015 3 31
---
Cycle : 54
**  2015 3 31  -  2014 12 29
---
Cycle : 54
**  2014 12 29  -  2015 3 31
---
Cycle : 54
**  2015 3 31  -  2015 3 31
---
Cycle : 55
**  2015 3 31  -  2015 4 1
---
Cycle : 56
**  2015 4 1  -  2014 5 4
---
Cycle : 57
**  2014 5 4  -  2014 5 5
---
Cycle : 58
**  2014 5 5  -  2014 5 7
---
Cycle : 59
**  2014 5 7  -  2014 5 7
---
Cycle : 60
**  2014 5 7  -  2014 5 8
---
Cycle : 60
**  2014 5 8  -  2014 7 4
---
Cycle : 61
**  2014 7 4  -  2015 4 7
---
Cycle : 62
**  2015 4 7  -  2015 4 7
---
Cycle : 63
**  2015 4 7  -  2015 4 8
---
Cycle : 63
**  2015 4 8  -  2015 4 8
---
Cycle : 63
**  2015 4 8  -  2015 4 8
---
Cycle : 63
**  2015 4 8  -  2015 4 8
---
Cycle : 63
**  2015 4 8  -  2015 4 8
---
Cycle : 63
**  2015 4 8  -  2015 4 8
---
Cycle : 63
**  2015 4 8  -  2015 4 8
---
Cycle : 64
**  2015 4 8  -  2015 4 10
---
Cycle : 65
**  2015 4 10  -  2015 4 11
---
Cycle : 66
**  2015 4 11  -  2015 4 12
---
Cycle : 67
**  2015 4 12  -  2015 4 13
---
Cycle : 68
**  2015 4 13  -  2015 4 14
---
Cycle : 69
**  2015 4 14  -  2015 4 14
---
Cycle : 70
**  2015 4 14  -  2015 4 15
---
Cycle : 70
**  2015 4 15  -  2015 4 15
---
Cycle : 70
**  2015 4 15  -  2015 4 15
---
Cycle : 71
**  2015 4 15  -  2015 4 11
---
Cycle : 72
**  2015 4 11  -  2015 4 12
---
Cycle : 73
**  2015 4 12  -  2014 10 18
---
Cycle : 74
**  2014 10 18  -  2015 4 14
---
Cycle : 75
**  2015 4 14  -  2015 4 15
---
Cycle : 75
**  2015 4 15  -  2015 4 15
---
Cycle : 76
**  2015 4 15  -  2015 4 22
---
Cycle : 77
**  2015 4 22  -  2014 12 10
---
Cycle : 78
**  2014 12 10  -  2013 11 27
---
Cycle : 79
**  2013 11 27  -  2015 4 24
---
Cycle : 80
**  2015 4 24  -  2015 4 25
---
Cycle : 80
**  2015 4 25  -  2015 4 25
---
Cycle : 80
**  2015 4 25  -  2015 4 25
---
Cycle : 80
**  2015 4 25  -  2015 4 25
---
Cycle : 80
**  2015 4 25  -  2015 4 25
---
Cycle : 80
**  2015 4 25  -  2015 4 25
---
Cycle : 80
**  2015 4 25  -  2015 4 25
---
Cycle : 80
**  2015 4 25  -  2015 4 25
---
Cycle : 80
**  2015 4 25  -  2015 1 11
---
Cycle : 81
**  2015 1 11  -  2014 9 12
---
Cycle : 82
**  2014 9 12  -  2014 9 13
---
Cycle : 82
**  2014 9 13  -  2014 9 13
---
Cycle : 82
**  2014 9 13  -  2014 9 13
---
Cycle : 82
**  2014 9 13  -  2014 9 13
---
Cycle : 83
**  2014 9 13  -  2014 11 23
---
Cycle : 84
**  2014 11 23  -  2015 4 29
---
Cycle : 85
**  2015 4 29  -  2014 9 2
---
Cycle : 86
**  2014 9 2  -  2015 5 1
---
Cycle : 87
**  2015 5 1  -  2015 5 2
---
Cycle : 88
**  2015 5 2  -  2015 4 28
---
Cycle : 89
**  2015 4 28  -  2015 5 4
---
Cycle : 90
**  2015 5 4  -  2015 4 30
---
Cycle : 91
**  2015 4 30  -  2015 5 5
---
Cycle : 92
**  2015 5 5  -  2015 5 2
---
Cycle : 93
**  2015 5 2  -  2015 5 9
---
Cycle : 94
**  2015 5 9  -  2015 5 10
---
Cycle : 95
**  2015 5 10  -  2015 5 11
---
Cycle : 96
**  2015 5 11  -  2015 5 4
---
Cycle : 97
**  2015 5 4  -  2015 5 5
---
Cycle : 98
**  2015 5 5  -  2015 3 25
---
Cycle : 99
**  2015 3 25  -  2015 5 14
---
Cycle : 100
**  2015 5 14  -  2015 5 15
---
Cycle : 100
**  2015 5 15  -  2015 5 15
---
Cycle : 100
**  2015 5 15  -  2015 5 15
---
Cycle : 101
**  2015 5 15  -  2015 5 17
---
Cycle : 102
**  2015 5 17  -  2015 5 17
---
Cycle : 103
**  2015 5 17  -  2014 11 17
---
Cycle : 104
**  2014 11 17  -  2015 5 19
---
Cycle : 105
**  2015 5 19  -  2015 5 20
---
Cycle : 105
**  2015 5 20  -  2015 5 20
---
Cycle : 106
**  2015 5 20  -  2015 5 22
---
Cycle : 107
**  2015 5 22  -  2015 5 17
---
Cycle : 108
**  2015 5 17  -  2015 5 23
---
Cycle : 109
**  2015 5 23  -  2015 2 15
---
Cycle : 109
**  2015 2 15  -  2015 5 24
---
Cycle : 109
**  2015 5 24  -  2015 5 24
---
Cycle : 109
**  2015 5 24  -  2015 5 24
---
Cycle : 109
**  2015 5 24  -  2015 5 24
---
Cycle : 109
**  2015 5 24  -  2015 5 24
---
Cycle : 109
**  2015 5 24  -  2015 5 21
---
Cycle : 110
**  2015 5 21  -  2015 5 23
---
Cycle : 111
**  2015 5 23  -  2015 5 26
---
Cycle : 112
**  2015 5 26  -  2015 5 27
---
Cycle : 113
**  2015 5 27  -  2014 12 15
---
Cycle : 114
**  2014 12 15  -  2014 12 16
---
Cycle : 114
**  2014 12 16  -  2014 12 16
---
Cycle : 114
**  2014 12 16  -  2014 12 16
---
Cycle : 115
**  2014 12 16  -  2015 5 30
---
Cycle : 116
**  2015 5 30  -  2015 5 31
---
Cycle : 117
**  2015 5 31  -  2015 6 1
---
Cycle : 118
**  2015 6 1  -  2015 6 2
---
Cycle : 119
**  2015 6 2  -  2015 6 3
---
Cycle : 120
**  2015 6 3  -  2015 6 5
---
Cycle : 121
**  2015 6 5  -  2015 6 5
---
Cycle : 122
**  2015 6 5  -  2015 6 6
---
Cycle : 123
**  2015 6 6  -  2015 6 7
---
Cycle : 123
**  2015 6 7  -  2015 6 7
---
Cycle : 123
**  2015 6 7  -  2015 6 7
---
Cycle : 123
**  2015 6 7  -  2015 6 7
---
Cycle : 123
**  2015 6 7  -  2015 6 7
---
Cycle : 123
**  2015 6 7  -  2015 6 7
---
Cycle : 123
**  2015 6 7  -  2015 6 7
---
Cycle : 123
**  2015 6 7  -  2015 6 7
---
Cycle : 123
**  2015 6 7  -  2015 6 7
---
Cycle : 124
**  2015 6 7  -  2015 6 5
---
Cycle : 125
**  2015 6 5  -  2015 6 9
---
Cycle : 126
**  2015 6 9  -  2015 6 7
---
Cycle : 127
**  2015 6 7  -  2015 6 11
---
Cycle : 128
**  2015 6 11  -  2015 6 12
---
Cycle : 128
**  2015 6 12  -  2015 6 12
---
Cycle : 128
**  2015 6 12  -  2015 6 12
---
Cycle : 128
**  2015 6 12  -  2015 6 12
---
Cycle : 128
**  2015 6 12  -  2015 6 12
---
Cycle : 129
**  2015 6 12  -  2015 5 22
---
Cycle : 130
**  2015 5 22  -  2014 10 12
---
Cycle : 131
**  2014 10 12  -  2015 5 24
---
Cycle : 132
**  2015 5 24  -  2014 11 1
---
Cycle : 133
**  2014 11 1  -  2015 6 17
---
Cycle : 134
**  2015 6 17  -  2015 6 18
---
Cycle : 134
**  2015 6 18  -  2015 6 18
---
Cycle : 134
**  2015 6 18  -  2015 6 18
---
Cycle : 134
**  2015 6 18  -  2015 6 18
---
Cycle : 135
**  2015 6 18  -  2015 6 20
---
Cycle : 136
**  2015 6 20  -  2015 3 4
---
Cycle : 137
**  2015 3 4  -  2015 3 5
---
Cycle : 137
**  2015 3 5  -  2015 3 5
---
Cycle : 137
**  2015 3 5  -  2015 3 5
---
Cycle : 137
**  2015 3 5  -  2015 3 23
---
Cycle : 137
**  2015 3 23  -  2015 3 23
---
Cycle : 137
**  2015 3 23  -  2015 6 21
---
Cycle : 137
**  2015 6 21  -  2015 6 21
---
Cycle : 137
**  2015 6 21  -  2015 6 21
---
Cycle : 137
**  2015 6 21  -  2015 6 21
---
Cycle : 138
**  2015 6 21  -  2015 6 23
---
Cycle : 139
**  2015 6 23  -  2015 4 11
---
Cycle : 140
**  2015 4 11  -  2015 3 29
---
Cycle : 141
**  2015 3 29  -  2015 4 14
---
Cycle : 142
**  2015 4 14  -  2015 3 31
---
Cycle : 143
**  2015 3 31  -  2015 4 29
---
Cycle : 144
**  2015 4 29  -  2015 6 28
---
Cycle : 144
**  2015 6 28  -  2015 6 28
---
Cycle : 144
**  2015 6 28  -  2015 6 28
---
Cycle : 145
**  2015 6 28  -  2014 8 17
---
Cycle : 146
**  2014 8 17  -  2015 7 1
---
Cycle : 147
**  2015 7 1  -  2015 7 1
---
Cycle : 148
**  2015 7 1  -  2015 7 2
---
Cycle : 149
**  2015 7 2  -  2015 4 16
---
Cycle : 150
**  2015 4 16  -  2015 7 4
---
Cycle : 151
**  2015 7 4  -  2014 6 4
---
Cycle : 151
**  2014 6 4  -  2014 6 4
---
Cycle : 151
**  2014 6 4  -  2014 6 4
---
Cycle : 152

**  2014 6 4  -  2014 6 5
---
Cycle : 153
**  2014 6 5  -  2015 7 7
---
Cycle : 154
**  2015 7 7  -  2015 7 9
---
Cycle : 155
**  2015 7 9  -  2015 7 10
---
Cycle : 156
**  2015 7 10  -  2015 4 24
---
Cycle : 157
**  2015 4 24  -  2015 7 11
---
Cycle : 158
**  2015 7 11  -  2015 7 13
---
Cycle : 159
**  2015 7 13  -  2015 7 14
---
Cycle : 160
**  2015 7 14  -  2015 7 15
---
Cycle : 161
**  2015 7 15  -  2015 7 16
---
Cycle : 162
**  2015 7 16  -  2015 7 9
---
Cycle : 163
**  2015 7 9  -  2015 7 18
---
Cycle : 164
**  2015 7 18  -  2015 7 19
---
Cycle : 164
**  2015 7 19  -  2015 7 19
---
Cycle : 164
**  2015 7 19  -  2015 7 19
---
Cycle : 164
**  2015 7 19  -  2015 6 21
---
Cycle : 164
**  2015 6 21  -  2015 7 19
---
Cycle : 164
**  2015 7 19  -  2015 7 19
---
Cycle : 164
**  2015 7 19  -  2015 7 19
---
Cycle : 164
**  2015 7 19  -  2015 7 19
---
Cycle : 165
**  2015 7 19  -  2015 7 20
---
Cycle : 166
**  2015 7 20  -  2015 7 21
---
Cycle : 167
**  2015 7 21  -  2015 7 22
---
Cycle : 168
**  2015 7 22  -  2015 7 17
---
Cycle : 169
**  2015 7 17  -  2015 7 18
---
Cycle : 170
**  2015 7 18  -  2015 7 25
---
Cycle : 171
**  2015 7 25  -  2015 7 26
---
Cycle : 172
**  2015 7 26  -  2015 7 26
---
Cycle : 173
**  2015 7 26  -  2015 7 27
---
Cycle : 174
**  2015 7 27  -  2015 5 3
---
Cycle : 175
**  2015 5 3  -  2015 7 30
---
Cycle : 176
**  2015 7 30  -  2015 7 25
---
Cycle : 177
**  2015 7 25  -  2015 8 1
---
Cycle : 178
**  2015 8 1  -  2015 8 2
---
Cycle : 178
**  2015 8 2  -  2015 7 28
---
Cycle : 178
**  2015 7 28  -  2015 7 28
---
Cycle : 179
**  2015 7 28  -  2015 8 3
---
Cycle : 180
**  2015 8 3  -  2015 7 29
---
Cycle : 181
**  2015 7 29  -  2015 7 30
---
Cycle : 181
**  2015 7 30  -  2015 7 30
---
Cycle : 182
**  2015 7 30  -  2015 7 14
---
Cycle : 183
**  2015 7 14  -  2014 11 3
---
Cycle : 184
**  2014 11 3  -  2015 8 6
---
Cycle : 185
**  2015 8 6  -  2015 8 8
---
Cycle : 186
**  2015 8 8  -  2015 4 29
---
Cycle : 187
**  2015 4 29  -  2015 8 10
---
Cycle : 188
**  2015 8 10  -  2017 8 29
---
Cycle : 188
**  2017 8 29  -  2017 8 29
---
Cycle : 188
**  2017 8 29  -  2017 8 29
---
Cycle : 188
**  2017 8 29  -  2017 8 29
---
Cycle : 188
**  2017 8 29  -  2017 8 29
---
Cycle : 188
**  2017 8 29  -  2017 8 29
---
Cycle : 188
**  2017 8 29  -  2017 8 29
---
Cycle : 188
**  2017 8 29  -  2017 8 29
---
Cycle : 188
**  2017 8 29  -  2017 8 29
---
Cycle : 189
**  2017 8 29  -  2017 8 30
---
Cycle : 190
**  2017 8 30  -  2017 8 31
---
Cycle : 191
**  2017 8 31  -  2017 9 1
---
Cycle : 191
**  2017 9 1  -  2017 9 1
---
Cycle : 192
**  2017 9 1  -  2017 9 2
---
Cycle : 193
**  2017 9 2  -  2017 9 3
---
Cycle : 194
**  2017 9 3  -  2017 9 4
---
Cycle : 195
**  2017 9 4  -  2017 9 5
---
Cycle : 196
**  2017 9 5  -  2017 9 6
---
Cycle : 197
**  2017 9 6  -  2017 9 7
---
Cycle : 198
**  2017 9 7  -  2017 9 8
---
Cycle : 199
**  2017 9 8  -  2017 9 9
---
Cycle : 200
**  2017 9 9  -  2017 9 10
---
Cycle : 201
**  2017 9 10  -  2017 9 11
---
Cycle : 201
**  2017 9 11  -  2017 9 11
---
Cycle : 202
**  2017 9 11  -  2017 9 12
---
Cycle : 203
**  2017 9 12  -  2017 9 13
---
Cycle : 204
**  2017 9 13  -  2017 9 14
---
Cycle : 205
**  2017 9 14  -  2017 9 15
---
Cycle : 206
**  2017 9 15  -  2017 9 16
---
Cycle : 207
**  2017 9 16  -  2017 9 17
---
Cycle : 207
**  2017 9 17  -  2017 9 17
---
Cycle : 207
**  2017 9 17  -  2017 9 17
---
Cycle : 207
**  2017 9 17  -  2017 9 17
---
Cycle : 208
**  2017 9 17  -  2017 9 18
---
Cycle : 209
**  2017 9 18  -  2017 9 19
---
Cycle : 209
**  2017 9 19  -  2017 9 19
---
Cycle : 209
**  2017 9 19  -  2017 9 19
---
Cycle : 209
**  2017 9 19  -  2017 9 19
---
Cycle : 209
**  2017 9 19  -  2017 9 19
---
Cycle : 210
**  2017 9 19  -  2017 9 20
---
Cycle : 211
**  2017 9 20  -  2017 9 21
---
Cycle : 212
**  2017 9 21  -  2017 9 22
---
Cycle : 213
**  2017 9 22  -  2017 9 23
---
Cycle : 214
**  2017 9 23  -  2017 9 24
---
Cycle : 215
**  2017 9 24  -  2017 9 25
---
Cycle : 216
**  2017 9 25  -  2017 9 26
---
Cycle : 217
**  2017 9 26  -  2017 9 27
---
Cycle : 218
**  2017 9 27  -  2017 9 28
---
Cycle : 219
**  2017 9 28  -  2017 9 29
---
Cycle : 220
**  2017 9 29  -  2017 9 30
---
Cycle : 220
**  2017 9 30  -  2017 9 30
---
Cycle : 221
**  2017 9 30  -  2017 10 1
---
Cycle : 222
**  2017 10 1  -  2017 10 2
---
Cycle : 223
**  2017 10 2  -  2017 10 3
---
Cycle : 224
**  2017 10 3  -  2017 10 4
---
Cycle : 224
**  2017 10 4  -  2017 10 4
---
Cycle : 224
**  2017 10 4  -  2017 10 4
---
Cycle : 225
**  2017 10 4  -  2017 10 5
---
Cycle : 226
**  2017 10 5  -  2017 10 6
---
Cycle : 226
**  2017 10 6  -  2017 10 6
---
Cycle : 227
**  2017 10 6  -  2017 10 7
---
Cycle : 228
**  2017 10 7  -  2017 10 8
---
Cycle : 228
**  2017 10 8  -  2017 10 8
---
Cycle : 229
**  2017 10 8  -  2017 10 9
---
Cycle : 230
**  2017 10 9  -  2017 10 10
---
Cycle : 231
**  2017 10 10  -  2017 10 11
---
Cycle : 232
**  2017 10 11  -  2017 10 12
---

In [71]:
df_final['LastRunFeature'] = days
df_final = df_final.drop('Hours', axis=1)
df_final.head()

,Name,Duration,LastRun,E1,E2,E3,Verdict,PRIORITY_VALUE,DIST,CHANGE_IN_STATUS,Cycle,LastRunFeature
0,4134,537.666667,2015-02-06,-1,-1,-1,-1,140.536188,1,0,1,2075
1,341,817.666667,2013-10-9,-1,-1,-1,-1,92.411253,1,0,2,485
2,348,509.666667,2015-2-8,-1,-1,1,-1,148.257051,2,1,3,-487
3,1335,300.333333,2015-1-31,1,1,1,1,251.592755,0,0,4,8
4,1515,1218.000000,2015-2-9,-1,-1,-1,-1,62.037413,1,0,5,-9

In [72]:

# replacing values in E1 E2 E3 for comparsion with RETECS
MF = df_final.loc[:,'E1':'E3'].values

rows = len(MF)
columns = len(MF[0])


E1 = []
E2 = []

E3 = []

i=0
for a, b, c in MF:
    i=i+1
    #print (a,b)
    if a==-1:
        E1.append(1)
    else:
        E1.append(0)
    if b==-1:
        E2.append(1)
    else:
        E2.append(0)
    if c==-1:
        E3.append(1)
    else:
        E3.append(0)

In [73]:
len(E3)

356

In [74]:
df_final['E1'] = E1
df_final['E2'] = E2
df_final['E3'] = E3

df_final.head()

,Name,Duration,LastRun,E1,E2,E3,Verdict,PRIORITY_VALUE,DIST,CHANGE_IN_STATUS,Cycle,LastRunFeature
0,4134,537.666667,2015-02-06,1,1,1,-1,140.536188,1,0,1,2075
1,341,817.666667,2013-10-9,1,1,1,-1,92.411253,1,0,2,485
2,348,509.666667,2015-2-8,1,1,0,-1,148.257051,2,1,3,-487
3,1335,300.333333,2015-1-31,0,0,0,1,251.592755,0,0,4,8
4,1515,1218.000000,2015-2-9,1,1,1,-1,62.037413,1,0,5,-9

In [75]:
# replacing values in Verdict for comparsion with RETECS
MF = df_final.loc[:,'Verdict'].values

rows = len(MF)

Verdict = []

i=0
for a in MF:
    i=i+1
    #print (a,b)
    if a==-1:
        Verdict.append(1)
    else:
        Verdict.append(0)

        
df_final['Verdict'] = Verdict

df_final.head()

,Name,Duration,LastRun,E1,E2,E3,Verdict,PRIORITY_VALUE,DIST,CHANGE_IN_STATUS,Cycle,LastRunFeature
0,4134,537.666667,2015-02-06,1,1,1,1,140.536188,1,0,1,2075
1,341,817.666667,2013-10-9,1,1,1,1,92.411253,1,0,2,485
2,348,509.666667,2015-2-8,1,1,0,1,148.257051,2,1,3,-487
3,1335,300.333333,2015-1-31,0,0,0,0,251.592755,0,0,4,8
4,1515,1218.000000,2015-2-9,1,1,1,1,62.037413,1,0,5,-9

In [76]:
# Import required modules
import pandas as pd
from sklearn import preprocessing

# Set charts to view inline
%matplotlib inline

In [77]:
df_final["Duration"] = df_final["Duration"].astype(int)

In [78]:
# Normalize LastRunFeature and Duration within range (0,5)
df_final["LastRunFeature"]=((df_final["LastRunFeature"]-df_final["LastRunFeature"].min())/(df_final["LastRunFeature"].max()-df_final["LastRunFeature"].min()))*1
df_final["DurationFeature"]=((df_final["Duration"]-df_final["Duration"].min())/(df_final["Duration"].max()-df_final["Duration"].min()))*1
df_final["PRIORITY_VALUE"]=((df_final["PRIORITY_VALUE"]-df_final["PRIORITY_VALUE"].min())/(df_final["PRIORITY_VALUE"].max()-df_final["PRIORITY_VALUE"].min()))*1

In [79]:
# save to csv
df_final.to_csv('Cisco.csv', index = False)

In [1791]:



df_final.head()

,Name,Duration,LastRun,E1,E2,E3,Verdict,PRIORITY_VALUE,DIST,CHANGE_IN_STATUS,Cycle,LastRunFeature,DurationFeature
0,4134,537,2015-02-06,1,1,1,1,0.006515,1,0,1,1.000000,0.006515
1,341,817,2013-10-9,1,1,1,1,0.010223,1,0,2,0.452381,0.010223
2,348,509,2015-2-8,1,1,0,1,0.006244,2,1,3,0.096337,0.006144
3,1335,300,2015-1-31,0,0,0,0,0.003532,0,0,4,0.277656,0.003377
4,1515,1218,2015-2-9,1,1,1,1,0.015524,1,0,5,0.271429,0.015533